# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_users_id', to='api.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_users_id', to='api.User'),
        ),
    ]
