# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170709_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('sentat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
        migrations.AddField(
            model_name='messages',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='api.users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='api.users'),
        ),
    ]
