# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170710_0706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='message',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
