# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170710_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='ids',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='ids',
        ),
    ]
